import {developments,materialTypes} from './data.js';
import {propertyCard,recentCard,price,badge,materialCard,escapeHTML} from './components.js';
const main=document.querySelector('main');
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function home(){main.innerHTML=`<section class="intro"><div class="eyebrow">Seu próximo negócio começa aqui</div><h1>Central de Empreendimentos</h1><p>Encontre o imóvel. Acesse os materiais. Apresente com confiança.</p><label class="search"><span aria-hidden="true">⌕</span><input id="search" type="search" placeholder="Busque por empreendimento, bairro ou construtora" aria-label="Buscar empreendimento, bairro ou construtora"></label></section><div class="container"><div class="filters"><span class="filter-label">Filtrar por</span>${[['builder','Construtoras'],['city','Cidades'],['status','Status']].map(([key,label])=>`<select id="${key}" aria-label="Filtrar ${label}"><option value="">${label}</option>${[...new Set(developments.map(p=>p[key]))].map(v=>`<option>${v}</option>`).join('')}</select>`).join('')}<button class="clear" id="clear" hidden>Limpar filtros</button></div><section id="catalogo"><div class="section-heading"><h2>Explore os empreendimentos</h2><span class="count" id="count" role="status" aria-live="polite"></span></div><div class="grid" id="results"></div></section><section class="recent" id="recentes"><div class="section-heading"><h2>Atualizados recentemente</h2><span class="count">Materiais em dia</span></div><div class="recent-grid">${[...developments].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).slice(0,3).map(recentCard).join('')}</div></section><p class="demo">Demonstração · Os empreendimentos, valores e materiais deste catálogo são fictícios. Fotografias ilustrativas.</p></div>`;
const ids=['search','builder','city','status'];const controls=ids.map(id=>document.getElementById(id));const update=()=>{const [q,b,c,s]=controls.map(x=>x.value);const items=developments.filter(p=>normalize(`${p.name} ${p.neighborhood} ${p.builder}`).includes(normalize(q.trim()))&&(!b||p.builder===b)&&(!c||p.city===c)&&(!s||p.status===s));document.querySelector('#count').textContent=`${items.length} ${items.length===1?'empreendimento':'empreendimentos'}`;document.querySelector('#results').innerHTML=items.length?items.map(propertyCard).join(''):'<div class="empty"><h3>Nenhum empreendimento encontrado</h3><p>Tente outro nome ou limpe os filtros para ver todos.</p></div>';document.querySelector('#clear').hidden=!controls.some(x=>x.value);};controls.forEach(x=>x.addEventListener(x.tagName==='INPUT'?'input':'change',update));document.querySelector('#clear').onclick=()=>{controls.forEach(x=>x.value='');update();};update();}
const id=new URLSearchParams(location.search).get('empreendimento');
if(!id)home();else main.innerHTML='<div class="container"><a class="back" href="/">Voltar ao catálogo</a><h1>Materiais do empreendimento</h1></div>';
function detail(p){document.title=`${p.name} — AUDAZ SQUAD`;const facts=[['Endereço',p.address,'address'],['Tipologia',p.typology],['Quartos',p.bedrooms],['Suítes',p.suites],['Metragem',`${p.minArea} a ${p.maxArea} m²`],['Vagas',p.parking],['Torres',p.towers],['Unidades',p.units],['Entrega',p.delivery]];main.innerHTML=`<div class="container"><a class="back" href="/">Voltar aos empreendimentos</a><section class="detail-hero"><img src="${p.image}" alt="Foto ilustrativa de edifício residencial" width="800" height="500"><div class="detail-heading">${badge(p.status)}<h1>${p.name}</h1><p>${p.builder}</p><p class="location">${p.neighborhood} · ${p.city}</p>${price(p.price)}</div></section><section class="info"><h2>O empreendimento</h2><div class="facts">${facts.map(([label,value,cls=''])=>`<div class="fact ${cls}"><small>${label}</small><strong>${escapeHTML(value)}</strong></div>`).join('')}</div></section><section class="materials" id="materiais"><div class="section-heading"><h2>Materiais Comerciais</h2><span class="count">${Object.values(p.materials).filter(m=>m?.url).length} materiais</span></div><div class="material-grid">${Object.keys(materialTypes).map(k=>materialCard(k,p.materials[k],materialTypes)).join('')}</div></section><p class="demo">Empreendimento fictício. Os arquivos são exemplos para demonstrar o catálogo; substitua pelos materiais oficiais. Localização indica apenas o bairro.</p></div>`;if(location.hash==='#materiais')requestAnimationFrame(()=>document.getElementById('materiais').scrollIntoView());}
if(id){const p=developments.find(p=>p.id===id);if(p)detail(p);else{document.title='Empreendimento não encontrado — AUDAZ SQUAD';main.innerHTML='<div class="container"><div class="empty"><h1>Empreendimento não encontrado</h1><p>O link pode ter sido alterado.</p><a class="action" href="/">Ver empreendimentos</a></div></div>';}}
