"""Interfaces required by use cases; implementations live in infrastructure."""

from typing import Protocol
from .entities import User, Development, Asset


class Transaction(Protocol):
    def commit(self) -> None: ...


class UserRepository(Transaction, Protocol):
    def users(self) -> list[User]: ...
    def user(self, user_id: str) -> User | None: ...
    def user_by_email(self, email: str) -> User | None: ...
    def save_user(self, user: User) -> None: ...


class CatalogRepository(Transaction, Protocol):
    def developments(self) -> list[Development]: ...
    def development(self, development_id: str) -> Development | None: ...
    def save_development(self, development: Development) -> None: ...
    def assets(self, development_id: str) -> list[Asset]: ...
    def asset(self, asset_id: str) -> Asset | None: ...
    def save_asset(self, asset: Asset) -> None: ...
    def delete_asset(self, asset_id: str) -> None: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, hashed: str) -> bool: ...


class FileStorage(Protocol):
    def put(self, content: bytes, kind: str) -> tuple[str, str]: ...
    def delete(self, key: str) -> None: ...
